---

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
    - vars/common_vars.yml
  roles:
    - common
  any_errors_fatal: true
  tags:
    - common

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  roles:
    - puregdal
  any_errors_fatal: true
  tags:
    - puregdal

- hosts: all
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
    - vars/purepdal_vars.yml
  roles:
    - purepdal
  any_errors_fatal: true
  tags:
    - purepdal

- hosts: minio
  gather_facts: yes
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/minio_vars.yml
  roles:
    - minio
  any_errors_fatal: true
  tags:
    - minio

- hosts: hadoop
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/minio_vars.yml
   - vars/hadoop_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  roles:
    - hadoop
  tags:
    - hadoop

- hosts: spark
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/hadoop_vars.yml
   - vars/spark_vars.yml
   - vars/minio_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
    HADOOP_LOG_DIR: "{{ hadoop_log_dir }}"
    HADOOP_CONF_DIR: "{{ hadoop_conf_dir }}"
  roles:
    - spark
  any_errors_fatal: true
  tags:
    - spark

- hosts: spark
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/pdal_vars.yml
  roles:
    - pdal
  tags:
    - pdal

- hosts: spark
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/pdal_vars.yml
   - vars/minio_vars.yml
   - vars/spark_vars.yml
   - vars/geotrellis_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
  roles:
    - geotrellis
  any_errors_fatal: true
  tags:
    - geotrellis

- hosts: cassandra
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/spark_vars.yml
   - vars/cassandra_vars.yml
  environment:
    JAVA_HOME: "{{ java_home }}"
  roles:
    - cassandra
  tags:
    - cassandra

- hosts: cassandra
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/hadoop_vars.yml
   - vars/spark_vars.yml
   - vars/cassandra_vars.yml
   - vars/geomesa_vars.yml
  environment:
    HADOOP_HOME: "{{ hadoop_usr_dir }}"
    CASSANDRA_HOME: "{{ cassandra_home_dir }}"
    JAVA_HOME: "{{ java_home }}"
  roles:
    - geomesa
  tags:
    - geomesa

- hosts: dask
  gather_facts: yes
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/common_vars.yml
   - vars/dask_vars.yml
  roles:
    - dask
  tags:
    - dask

- hosts: jupyterhub
  gather_facts: no
  remote_user: ubuntu
  become: true
  vars_files:
   - vars/spark_vars.yml
   - vars/common_vars.yml
   - vars/jupyterhub_vars.yml
  roles:
    - jupyterhub
  tags:
    - jupyterhub
