---
- name: ensure lcmacropipeline directory exists
  file: path="{{ emma_modules_dir }}/lcMacroPipe" state=directory group=users mode=g+rw

- name: Download lcmacropipeline
  git:
    repo: https://github.com/eEcoLiDAR/lcMacroPipeline.git
    dest: "{{ emma_modules_dir }}/lcMacroPipe/lcMacroPipeline"
    version: "development"
    update: no

- name: install jupyterlab dependencies for lcMacroPipeline
  pip:
    name:
      - jupyterlab
      - jupyter-server-proxy
    executable: {{ pip_executable }}

- name: Install lcMacroPipeline
  pip:
    name:
      - "{{ emma_modules_dir }}/lcMacroPipe/lcMacroPipeline/."
    executable: {{ pip_executable }}
